import { cp, mkdir, mkdtemp, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import * as tar from "tar";

const OWNER = "ShikemokuMK";
const REPOSITORY = "tyranoscript";
const REPOSITORY_URL = `https://github.com/${OWNER}/${REPOSITORY}`;

export interface CreateProjectOptions {
  directory: string;
  projectId?: string;
  title?: string;
  engineVersion?: string;
}

export interface CreateProjectResult {
  path: string;
  engineCommit: string;
}

interface ResolvedEngine {
  requestedRevision: string;
  commit: string;
}

export function resolveSettings(options: CreateProjectOptions): Required<CreateProjectOptions> {
  const directory = resolve(options.directory);
  const inferredId = basename(directory);
  const projectId = options.projectId ?? inferredId;
  const title = options.title ?? projectId;
  const engineVersion = options.engineVersion ?? "master";

  if (!/^[A-Za-z0-9_-]+$/.test(projectId)) {
    throw new Error("Project ID must contain only ASCII letters, digits, hyphens, and underscores.");
  }
  if (/[\r\n"]/.test(title)) {
    throw new Error("Title must not contain a newline or double quote.");
  }
  if (engineVersion.length === 0) throw new Error("Engine version must not be empty.");
  return { directory, projectId, title, engineVersion };
}

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url, { headers: { Accept: "application/vnd.github+json" } });
  if (!response.ok) throw new Error(`GitHub could not resolve the engine revision (${response.status} ${response.statusText}).`);
  return response.json();
}

export async function resolveEngineRevision(requestedRevision: string): Promise<ResolvedEngine> {
  const url = `https://api.github.com/repos/${OWNER}/${REPOSITORY}/commits/${encodeURIComponent(requestedRevision)}`;
  const result = await fetchJson(url);
  if (!result || typeof result !== "object" || !("sha" in result) || typeof result.sha !== "string" || !/^[0-9a-f]{40}$/i.test(result.sha)) {
    throw new Error("GitHub returned an invalid commit for the engine revision.");
  }
  return { requestedRevision, commit: result.sha };
}

async function downloadArchive(commit: string, destination: string): Promise<void> {
  const response = await fetch(`https://codeload.github.com/${OWNER}/${REPOSITORY}/tar.gz/${commit}`);
  if (!response.ok) throw new Error(`Could not download the TyranoScript archive (${response.status} ${response.statusText}).`);
  await writeFile(destination, Buffer.from(await response.arrayBuffer()));
}

async function projectSourceRoot(extractionDirectory: string): Promise<string> {
  const entries = await readdir(extractionDirectory, { withFileTypes: true });
  const directories = entries.filter((entry) => entry.isDirectory());
  if (directories.length !== 1) throw new Error("The TyranoScript archive has an unexpected directory layout.");
  return join(extractionDirectory, directories[0].name);
}

async function replaceConfigMetadata(configPath: string, projectId: string, title: string): Promise<void> {
  const config = await readFile(configPath, "utf8");
  const withId = config.replace(/^\s*;projectID\s*=.*$/m, `;projectID = ${projectId};`);
  const withTitle = withId.replace(/^\s*;System\.title\s*=.*$/m, `;System.title = "${title}";`);
  if (withTitle === config || !/;projectID\s*=/.test(config) || !/;System\.title\s*=/.test(config)) {
    throw new Error("The TyranoScript Config.tjs template is missing projectID or System.title.");
  }
  await writeFile(configPath, withTitle, "utf8");
}

function helloWorldScenario(title: string): string {
  return `; Generated by monog\n[title name="${title}"]\n[layopt layer="message" visible="true"]\n\nHello, World!\n[s]\n`;
}

async function writeProjectFiles(source: string, destination: string, projectId: string, title: string, engine: ResolvedEngine): Promise<void> {
  await cp(join(source, "tyrano"), join(destination, "tyrano"), { recursive: true, errorOnExist: true });
  await mkdir(join(destination, "data", "system"), { recursive: true });
  await mkdir(join(destination, "data", "scenario"), { recursive: true });
  await cp(join(source, "index.html"), join(destination, "index.html"));
  await cp(join(source, "data", "system", "Config.tjs"), join(destination, "data", "system", "Config.tjs"));
  await cp(join(source, "data", "system", "KeyConfig.js"), join(destination, "data", "system", "KeyConfig.js"));
  await replaceConfigMetadata(join(destination, "data", "system", "Config.tjs"), projectId, title);
  await writeFile(join(destination, "data", "scenario", "first.ks"), helloWorldScenario(title), "utf8");
  await writeFile(join(destination, "package.json"), `${JSON.stringify({ private: true, monog: {
    engine: { repository: REPOSITORY_URL, requestedRevision: engine.requestedRevision, commit: engine.commit },
    generatedAt: new Date().toISOString(),
  } }, null, 2)}\n`, "utf8");
}

export async function createProject(options: CreateProjectOptions): Promise<CreateProjectResult> {
  const settings = resolveSettings(options);
  try {
    await stat(settings.directory);
    throw new Error(`Output directory already exists: ${settings.directory}`);
  } catch (error: unknown) {
    if (!(error && typeof error === "object" && "code" in error && error.code === "ENOENT")) throw error;
  }

  const engine = await resolveEngineRevision(settings.engineVersion);
  const parent = dirname(settings.directory);
  await mkdir(parent, { recursive: true });
  const temporary = await mkdtemp(join(parent, ".monog-"));
  const archive = join(await mkdtemp(join(tmpdir(), "monog-archive-")), "tyranoscript.tar.gz");
  const archiveDirectory = dirname(archive);

  try {
    await downloadArchive(engine.commit, archive);
    const extractionDirectory = await mkdtemp(join(tmpdir(), "monog-extract-"));
    try {
      await tar.x({ cwd: extractionDirectory, file: archive, strict: true });
      const source = await projectSourceRoot(extractionDirectory);
      await writeProjectFiles(source, temporary, settings.projectId, settings.title, engine);
    } finally {
      await rm(extractionDirectory, { recursive: true, force: true });
    }
    await rename(temporary, settings.directory);
    return { path: settings.directory, engineCommit: engine.commit };
  } catch (error) {
    await rm(temporary, { recursive: true, force: true });
    throw error;
  } finally {
    await rm(archiveDirectory, { recursive: true, force: true });
  }
}
